.TH MSEED2ASCII 1 2008/04/22
.SH NAME
Mini-SEED to ASCII converter

.SH SYNOPSIS
.nf
mseed2ascii [options] file1 [file2 file3 ...]

.fi
.SH DESCRIPTION
\fBmseed2ascii\fP converts Mini-SEED time-series data to ASCII format.
By default all aspects of the input files are automatically detected
(record length, byte order, etc.).  If an input file name is prefixed
with an '@' character the file is assumed to contain a list of input
data files, see \fILIST FILES\fP below.

A separate output file is written for each continuous time-series in
the input data.  Output file names are of the form:

.nf
"Net.Sta.Loc.Chan.Qual.YYYY-MM-DDTHH:MM:SS.FFFFFF.ASCII"

For example:
"TA.ELFS..LHZ.R.2006-04-22T15:36:19.000000.ASCII"
.fi

If the input file name is "-" input Mini-SEED records will be read
from standard input.

.SH OPTIONS

.IP "-V         "
Print program version and exit.

.IP "-h         "
Print program usage and exit.

.IP "-v         "
Be more verbose.  This flag can be used multiple times ("-v -v" or
"-vv") for more verbosity.

.IP "-r \fIbytes\fP"
Specify the Mini-SEED record length in \fIbytes\fP, by default this is
autodetected.

.IP "-i         "
Process each input file individually.  By default all input files are
read and all data is buffered in memory before ASCII files are written.
This allows time-series spanning mutilple input files to be merged and
written in a single ASCII file.  The intention is to use this option
when processing large amounts of data in order to keep memory usage
within reasonable limits.

.IP "-tt \fIsecs\fP"
Specify a time tolerance for constructing continous trace segments.
The tolerance is specified in seconds.  The default tolerance is 1/2
of the sample period.

.IP "-rt \fIdiff\fP"
Specify a sample rate tolerance for constructing continous trace
segments.  The tolerance is specified as the difference between two
sampling rates.  The default tolerance is tested as: (abs(1-sr1/sr2) <
0.0001).

.IP "-f \fIformat\fP"
The default output format is sample list.  This option applies to all
output files:

.nf
1 : Sample list format, header includes time stamp of first
2 : Time-sample pair format, each sample value listed with time stamp
.fi

.SH LIST FILES
If an input file is prefixed with an '@' character the file is assumed
to contain a list of file for input.  Multiple list files can be
combined with multiple input files on the command line.  The last,
space separated field on each line is assumed to be the file name to
be read.

An example of a simple text list:

.nf
TA.ELFS..LHE.R.mseed
TA.ELFS..LHN.R.mseed
TA.ELFS..LHZ.R.mseed
.fi

.SH AUTHOR
.nf
Chad Trabant
IRIS Data Management Center
.fi
