#
# Nmake file - Windows version
# Use 'nmake -f Makefile.win'

NODEBUG=1

!include <ntwin32.mak>

INCS = /I..\libmseed
LIBS = ..\libmseed\libmseed.lib
OPTS = -D_CRT_SECURE_NO_WARNINGS

BIN = ..\mseed2ascii.exe

cflags = $(cflags) -DWIN32

all: $(BIN)

$(BIN):	mseed2ascii.obj
	link.exe /nologo /out:$(BIN) $(LIBS) mseed2ascii.obj

.c.obj:
   $(cc) /nologo $(cflags) $(cdebug) $(cvarsmt) $(tflags) $(INCS) $(OPTS) $<

# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~ $(BIN)
